# This is a basic workflow to help you get started with Actions

  name: CILinux

  on:
    workflow_dispatch:

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  jobs:
    # This workflow contains a single job called "build"
    build:
      # The type of runner that the job will run on
      runs-on: ubuntu-20.04

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
        
        - name: Install Ninja And Deps
          run: sudo tools/install_dependencies.sh

        - name: Sync Deps
          run: python tools/git-sync-deps
          
        - name: Prepare Workspace
          run: |
            mkdir -p out/Shared
            cp .github/workflows/args_linux_static.gn out/Shared/args.gn
        
        - name: Run GN
          run: bin/gn gen ./out/Shared
            
            
        - name: Build Skia
          run: ninja -C ./out/Shared/
         
        - name: Bundle Artifacts
          run: cp -R include ./out/Shared/include
            
        - uses: actions/upload-artifact@v2
          with:
            name: skia_linux64
            path: out/Shared
