  # This is a basic workflow to help you get started with Actions

  name: CI

  # Controls when the workflow will run
  on:
    # Triggers the workflow on push or pull request events but only for the main branch
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  jobs:
    # This workflow contains a single job called "build"
    build:
      # The type of runner that the job will run on
      runs-on: windows-2019

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
        
        - name: Install Ninja
          uses: crazy-max/ghaction-chocolatey@v1
          with:
            args: install ninja

#         - name: Sync Deps
#           run: python tools/git-sync-deps
          
        - name: Prepare Workspace
          run: |
            mkdir out/Shared
            cp .github/workflows/args_win_static.gn out/Shared/args.gn
        
#         - name: Run GN
#           run: bin/gn gen out/Shared
            
            
        - name: Build Skia
          run: copy README .\out\Shared\ #ninja -C .\out\Shared\
         
        - name: Bundle Artifacts
          run: Copy-Item 'include' -Destination 'out\Shared\' -Recurse
            
        - uses: actions/upload-artifact@v2
          with:
            name: skia_winx64
            path: out/Shared # or path/to/artifact  
